name:                guess-numbers
version:             0.1.0.0
github:              "githubuser/guess-numbers"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/guess-numbers#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.2.1

library:
  source-dirs: src

executables:
  guess-numbers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - guess-numbers

